apiVersion: v1
kind: Service
metadata:
  name: "service1"
  labels:
    app: "service1"
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
  selector:
    app: "service1"
