apiVersion: apps/v1
kind: Deployment
metadata:
  name: "service2"
  labels:
    app.kubernetes.io/name: "service2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "service2"
  template:
    metadata:
      labels:
        app: "service2"
    spec:
      containers:
        - name: "service1"
          image: "tsangste/kube-workshop-service2:latest"
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
